### ISSUE TITLE
DeleteStreamAsync Not Exposed to Package Consumers

### ISSUE THREAD

**Issue by Anders-Toegersen** [atc-net/atc-cosmos-eventstore#57]
**Describe the issue**
Currently the `DeleteStreamAsync()` functionality is not exposed to the package consumer. It is unclear whether this exclusion is intentional or an oversight.

**Suggestion 1**
Move `DeleteStreamAsync()` with implementation from `IEventStoreManagementClient` to `IEventStoreClient`.

**Suggestion 2**
Make `IEventStoreManagementClient` public and move the internal access modifier to the unimplemented methods.

I'm happy to help with code changes. I just need to know which approach is preferred :)

**Comment by LarsSkovslund** [comment]
I think suggestion 1 is the optimal way, and we should remove the `IEventStoreManagementClient` from the package entirely.

@Anders-Toegersen, I would be grateful if you would implement the changes.

> @TomMalow this would also help you with the event-store data migration.

Cheers and happy holidays
